# Generated by Django 5.2.5 on 2025-08-11 14:32

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="Полное имя автора"),
                ),
                (
                    "date_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название книги"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Описание книги"),
                ),
                ("published", models.DateField(verbose_name="Дата публикации")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Стоимость книги"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to=books.models.path_for_preview,
                        verbose_name="Изображение книги",
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        to="books.author", verbose_name="Автор книги"
                    ),
                ),
            ],
        ),
    ]
